openapi: 3.0.1
info:
  title: Hangar API
  description: |-
    This page describes the format for the current Hangar REST API as well as general usage guidelines.<br>
    Note that all routes **not** listed here should be considered **internal**, and can change at a moment's notice. **Do not use them**.

    ## Authentication and Authorization
    There are two ways to consume the API: Authenticated or anonymous.

    ### Anonymous
    When using anonymous authentication, you only have access to public information, but you don't need to worry about creating and storing an API key or handing JWTs.

    ### Authenticated
    If you need access to non-public content or actions, you need to create and use API keys.
    These can be created by going to the API keys page via the profile dropdown or by going to your user page and clicking on the key icon.

    API keys allow you to impersonate yourself, so they should be handled like passwords. **Do not share them with anyone else!**

    #### Getting and Using a JWT
    Once you have an API key, you need to authenticate yourself: Send a `POST` request with your API key identifier to `/api/v1/authenticate?apiKey=yourKey`.
    The response will contain your JWT as well as an expiration time.
    Put this JWT into the `Authorization` header of every request and make sure to request a new JWT after the expiration time has passed.

    Please also set a meaningful `User-Agent` header. This allows us to better identify loads and needs for potentially new endpoints.

    ## Misc
    ### Date Formats
    Standard ISO types. Where possible, we use the [OpenAPI format modifier](https://swagger.io/docs/specification/data-models/data-types/#format).

    ### Rate Limits and Caching
    The default rate limit is set at 20 requests every 5 seconds with an initial overdraft for extra leniency.
    Individual endpoints, such as version creation, may have stricter rate limiting.

    If applicable, always cache responses. The Hangar API itself is cached by CloudFlare and internally.
  version: "1.0"
servers:
  - url: https://hangar.papermc.dev
    description: Generated server url
paths:
  /api/v1/projects/{author}/{slug}/upload:
    post:
      tags:
        - Versions
      summary: Creates a new version
      description: Creates a new version for a project. Requires the `create_version`
        permission in the project or owning organization.
      operationId: uploadVersion
      security:
        - HangarAuth:
            - create_version
  /api/v1/keys:
    get:
      tags:
        - API Keys
      summary: Fetches a list of API Keys
      description: Fetches a list of API Keys. Requires the `edit_api_keys` permission.
      operationId: getKeys
      security:
        - HangarAuth:
            - edit_api_keys
    post:
      tags:
        - API Keys
      summary: Creates an API key
      description: Creates an API key. Requires the `edit_api_keys` permission.
      operationId: createKey
      security:
        - HangarAuth:
            - edit_api_keys
    delete:
      tags:
        - API Keys
      summary: Deletes an API key
      description: Deletes an API key. Requires the `edit_api_keys` permission.
      operationId: deleteKey
      security:
        - HangarAuth:
            - edit_api_keys
  /api/v1/authenticate:
    post:
      tags:
        - Authentication
      summary: Creates an API JWT
      description: "`Log-in` with your API key in order to be able to call other endpoints\
        \ authenticated. The returned JWT should be specified as a header in all following\
        \ requests: `Authorization: HangarAuth your.jwt`"
      operationId: authenticate
  /api/v1/users:
    get:
      tags:
        - Users
      summary: Searches for users
      description: Returns a list of users based on a search query. Requires the `view_public_info`
        permission.
      operationId: showUsers
      security:
        - HangarAuth:
            - view_public_info
  /api/v1/users/{user}:
    get:
      tags:
        - Users
      summary: Returns a specific user
      description: Returns a specific user. Requires the `view_public_info` permission.
      operationId: getUser
      security:
        - HangarAuth:
            - view_public_info
  /api/v1/users/{user}/watching:
    get:
      tags:
        - Users
      summary: Returns the watched projects for a specific user
      description: Returns the watched projects for a specific user. Requires the
        `view_public_info` permission.
      operationId: getUserWatching
      security:
        - HangarAuth:
            - view_public_info
  /api/v1/users/{user}/starred:
    get:
      tags:
        - Users
      summary: Returns the starred projects for a specific user
      description: Returns the starred projects for a specific user. Requires the
        `view_public_info` permission.
      operationId: showStarred
      security:
        - HangarAuth:
            - view_public_info
  /api/v1/users/{user}/pinned:
    get:
      tags:
        - Users
      summary: Returns the pinned projects for a specific user
      description: Returns the pinned projects for a specific user. Requires the `view_public_info`
        permission.
      operationId: getUserPinnedProjects
      security:
        - HangarAuth:
            - view_public_info
  /api/v1/staff:
    get:
      tags:
        - Users
      summary: Returns Hangar staff
      description: Returns Hanagr staff. Requires the `view_public_info` permission.
      operationId: getStaff
      security:
        - HangarAuth:
            - view_public_info
  /api/v1/projects:
    get:
      tags:
        - Projects
      summary: Searches the projects on Hangar
      description: "Searches all the projects on Hangar, or for a single user. Requires\
        \ the `view_public_info` permission."
      operationId: getProjects
      security:
        - HangarAuth:
            - view_public_info
  /api/v1/projects/{author}/{slug}:
    get:
      tags:
        - Projects
      summary: Returns info on a specific project
      description: Returns info on a specific project. Requires the `view_public_info`
        permission.
      operationId: getProject
      security:
        - HangarAuth:
            - view_public_info
  /api/v1/projects/{author}/{slug}/watchers:
    get:
      tags:
        - Projects
      summary: Returns the watchers of a project
      description: Returns the watchers of a project. Requires the `view_public_info`
        permission.
      operationId: getProjectWatchers
      security:
        - HangarAuth:
            - view_public_info
  /api/v1/projects/{author}/{slug}/versions:
    get:
      tags:
        - Versions
      summary: Returns all versions of a project
      description: Returns all versions of a project. Requires the `view_public_info`
        permission in the project or owning organization.
      operationId: listVersions
      security:
        - HangarAuth:
            - view_public_info
  /api/v1/projects/{author}/{slug}/versions/{name}:
    get:
      tags:
        - Versions
      summary: Returns a specific version of a project
      description: Returns a specific version of a project. Requires the `view_public_info`
        permission in the project or owning organization.
      operationId: showVersion
      security:
        - HangarAuth:
            - view_public_info
  /api/v1/projects/{author}/{slug}/versions/{name}/{platform}/stats:
    get:
      tags:
        - Versions
      summary: Returns the stats for a version
      description: Returns the stats (downloads) for a version per day for a certain
        date range. Requires the `is_subject_member` permission.
      operationId: showVersionStats
      security:
        - HangarAuth:
            - is_subject_member
  /api/v1/projects/{author}/{slug}/versions/{name}/{platform}/download:
    get:
      tags:
        - Versions
      summary: Downloads a version
      description: Downloads the file for a specific platform of a version. Requires
        visibility of the project and version.
      operationId: downloadVersion
      security:
        - HangarAuth: []
  /api/v1/projects/{author}/{slug}/stats:
    get:
      tags:
        - Projects
      summary: Returns the stats for a project
      description: Returns the stats (downloads and views) for a project per day for
        a certain date range. Requires the `is_subject_member` permission.
      operationId: showProjectStats
      security:
        - HangarAuth:
            - is_subject_member
  /api/v1/projects/{author}/{slug}/stargazers:
    get:
      tags:
        - Projects
      summary: Returns the stargazers of a project
      description: Returns the stargazers of a project. Requires the `view_public_info`
        permission.
      operationId: getProjectStargazers
      security:
        - HangarAuth:
            - view_public_info
  /api/v1/projects/{author}/{slug}/members:
    get:
      tags:
        - Projects
      summary: Returns the members of a project
      description: Returns the members of a project. Requires the `view_public_info`
        permission.
      operationId: getProjectMembers
      security:
        - HangarAuth:
            - view_public_info
  /api/v1/permissions:
    get:
      tags:
        - Permissions
      summary: Returns your permissions
      description: Returns a list of permissions you have in the given context
      operationId: showPermissions
      security:
        - HangarAuth: []
  /api/v1/permissions/hasAny:
    get:
      tags:
        - Permissions
      summary: Checks whether you have at least one of the provided permissions
      description: Checks whether you have at least one of the provided permissions
        in the given context
      operationId: hasAny
      security:
        - HangarAuth: []
  /api/v1/permissions/hasAll:
    get:
      tags:
        - Permissions
      summary: Checks whether you have all the provided permissions
      description: Checks whether you have all the provided permissions in the given
        context
      operationId: hasAll
      security:
        - HangarAuth: []
  /api/v1/authors:
    get:
      tags:
        - Users
      summary: Returns all users with at least one public project
      description: Returns all users that have at least one public project. Requires
        the `view_public_info` permission.
      operationId: getAuthors
      security:
        - HangarAuth:
            - view_public_info
components:
  securitySchemes:
    HangarAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
