/*
 * Hangar API
 * This page describes the format for the current Hangar REST API as well as general usage guidelines.<br> Note that all routes **not** listed here should be considered **internal**, and can change at a moment's notice. **Do not use them**.  ## Authentication and Authorization There are two ways to consume the API: Authenticated or anonymous.  ### Anonymous When using anonymous authentication, you only have access to public information, but you don't need to worry about creating and storing an API key or handing JWTs.  ### Authenticated If you need access to non-public content or actions, you need to create and use API keys. These can be created by going to the API keys page via the profile dropdown or by going to your user page and clicking on the key icon.  API keys allow you to impersonate yourself, so they should be handled like passwords. **Do not share them with anyone else!**  #### Getting and Using a JWT Once you have an API key, you need to authenticate yourself: Send a `POST` request with your API key identifier to `/api/v1/authenticate?apiKey=yourKey`. The response will contain your JWT as well as an expiration time. Put this JWT into the `Authorization` header of every request and make sure to request a new JWT after the expiration time has passed.  Please also set a meaningful `User-Agent` header. This allows us to better identify loads and needs for potentially new endpoints.  ## Misc ### Date Formats Standard ISO types. Where possible, we use the [OpenAPI format modifier](https://swagger.io/docs/specification/data-models/data-types/#format).  ### Rate Limits and Caching The default rate limit is set at 20 requests every 5 seconds with an initial overdraft for extra leniency. Individual endpoints, such as version creation, may have stricter rate limiting.  If applicable, always cache responses. The Hangar API itself is cached by CloudFlare and internally.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bentzin.hangar.api.client.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;
import de.bentzin.hangar.api.client.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

/**
 * ProjectStats
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-27T18:55:17.902236655+01:00[Europe/Berlin]")
public class ProjectStats {
  public static final String SERIALIZED_NAME_VIEWS = "views";
  @SerializedName(SERIALIZED_NAME_VIEWS)
  private Long views;

  public static final String SERIALIZED_NAME_DOWNLOADS = "downloads";
  @SerializedName(SERIALIZED_NAME_DOWNLOADS)
  private Long downloads;

  public static final String SERIALIZED_NAME_RECENT_VIEWS = "recentViews";
  @SerializedName(SERIALIZED_NAME_RECENT_VIEWS)
  private Long recentViews;

  public static final String SERIALIZED_NAME_RECENT_DOWNLOADS = "recentDownloads";
  @SerializedName(SERIALIZED_NAME_RECENT_DOWNLOADS)
  private Long recentDownloads;

  public static final String SERIALIZED_NAME_STARS = "stars";
  @SerializedName(SERIALIZED_NAME_STARS)
  private Long stars;

  public static final String SERIALIZED_NAME_WATCHERS = "watchers";
  @SerializedName(SERIALIZED_NAME_WATCHERS)
  private Long watchers;

  public ProjectStats() {
  }

  public ProjectStats views(Long views) {
    
    this.views = views;
    return this;
  }

   /**
   * Get views
   * @return views
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getViews() {
    return views;
  }


  public void setViews(Long views) {
    this.views = views;
  }


  public ProjectStats downloads(Long downloads) {
    
    this.downloads = downloads;
    return this;
  }

   /**
   * Get downloads
   * @return downloads
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getDownloads() {
    return downloads;
  }


  public void setDownloads(Long downloads) {
    this.downloads = downloads;
  }


  public ProjectStats recentViews(Long recentViews) {
    
    this.recentViews = recentViews;
    return this;
  }

   /**
   * Get recentViews
   * @return recentViews
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getRecentViews() {
    return recentViews;
  }


  public void setRecentViews(Long recentViews) {
    this.recentViews = recentViews;
  }


  public ProjectStats recentDownloads(Long recentDownloads) {
    
    this.recentDownloads = recentDownloads;
    return this;
  }

   /**
   * Get recentDownloads
   * @return recentDownloads
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getRecentDownloads() {
    return recentDownloads;
  }


  public void setRecentDownloads(Long recentDownloads) {
    this.recentDownloads = recentDownloads;
  }


  public ProjectStats stars(Long stars) {
    
    this.stars = stars;
    return this;
  }

   /**
   * Get stars
   * @return stars
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getStars() {
    return stars;
  }


  public void setStars(Long stars) {
    this.stars = stars;
  }


  public ProjectStats watchers(Long watchers) {
    
    this.watchers = watchers;
    return this;
  }

   /**
   * Get watchers
   * @return watchers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getWatchers() {
    return watchers;
  }


  public void setWatchers(Long watchers) {
    this.watchers = watchers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectStats projectStats = (ProjectStats) o;
    return Objects.equals(this.views, projectStats.views) &&
        Objects.equals(this.downloads, projectStats.downloads) &&
        Objects.equals(this.recentViews, projectStats.recentViews) &&
        Objects.equals(this.recentDownloads, projectStats.recentDownloads) &&
        Objects.equals(this.stars, projectStats.stars) &&
        Objects.equals(this.watchers, projectStats.watchers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(views, downloads, recentViews, recentDownloads, stars, watchers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectStats {\n");
    sb.append("    views: ").append(toIndentedString(views)).append("\n");
    sb.append("    downloads: ").append(toIndentedString(downloads)).append("\n");
    sb.append("    recentViews: ").append(toIndentedString(recentViews)).append("\n");
    sb.append("    recentDownloads: ").append(toIndentedString(recentDownloads)).append("\n");
    sb.append("    stars: ").append(toIndentedString(stars)).append("\n");
    sb.append("    watchers: ").append(toIndentedString(watchers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("views");
    openapiFields.add("downloads");
    openapiFields.add("recentViews");
    openapiFields.add("recentDownloads");
    openapiFields.add("stars");
    openapiFields.add("watchers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ProjectStats
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ProjectStats.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProjectStats is not found in the empty JSON string", ProjectStats.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ProjectStats.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ProjectStats` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProjectStats.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProjectStats' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProjectStats> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProjectStats.class));

       return (TypeAdapter<T>) new TypeAdapter<ProjectStats>() {
           @Override
           public void write(JsonWriter out, ProjectStats value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProjectStats read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProjectStats given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProjectStats
  * @throws IOException if the JSON string is invalid with respect to ProjectStats
  */
  public static ProjectStats fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProjectStats.class);
  }

 /**
  * Convert an instance of ProjectStats to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

