/*
 * Hangar API
 * This page describes the format for the current Hangar REST API as well as general usage guidelines.<br> Note that all routes **not** listed here should be considered **internal**, and can change at a moment's notice. **Do not use them**.  ## Authentication and Authorization There are two ways to consume the API: Authenticated or anonymous.  ### Anonymous When using anonymous authentication, you only have access to public information, but you don't need to worry about creating and storing an API key or handing JWTs.  ### Authenticated If you need access to non-public content or actions, you need to create and use API keys. These can be created by going to the API keys page via the profile dropdown or by going to your user page and clicking on the key icon.  API keys allow you to impersonate yourself, so they should be handled like passwords. **Do not share them with anyone else!**  #### Getting and Using a JWT Once you have an API key, you need to authenticate yourself: Send a `POST` request with your API key identifier to `/api/v1/authenticate?apiKey=yourKey`. The response will contain your JWT as well as an expiration time. Put this JWT into the `Authorization` header of every request and make sure to request a new JWT after the expiration time has passed.  Please also set a meaningful `User-Agent` header. This allows us to better identify loads and needs for potentially new endpoints.  ## Misc ### Date Formats Standard ISO types. Where possible, we use the [OpenAPI format modifier](https://swagger.io/docs/specification/data-models/data-types/#format).  ### Rate Limits and Caching The default rate limit is set at 20 requests every 5 seconds with an initial overdraft for extra leniency. Individual endpoints, such as version creation, may have stricter rate limiting.  If applicable, always cache responses. The Hangar API itself is cached by CloudFlare and internally.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bentzin.hangar.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * User
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-28T17:51:10.536335800+01:00[Europe/Berlin]")
public class User {
  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TAGLINE = "tagline";
  @SerializedName(SERIALIZED_NAME_TAGLINE)
  private String tagline;

  public static final String SERIALIZED_NAME_JOIN_DATE = "joinDate";
  @SerializedName(SERIALIZED_NAME_JOIN_DATE)
  private OffsetDateTime joinDate;

  public static final String SERIALIZED_NAME_ROLES = "roles";
  @SerializedName(SERIALIZED_NAME_ROLES)
  private List<GlobalRole> roles = null;

  public static final String SERIALIZED_NAME_PROJECT_COUNT = "projectCount";
  @SerializedName(SERIALIZED_NAME_PROJECT_COUNT)
  private Long projectCount;

  public static final String SERIALIZED_NAME_LOCKED = "locked";
  @SerializedName(SERIALIZED_NAME_LOCKED)
  private Boolean locked;

  public static final String SERIALIZED_NAME_NAME_HISTORY = "nameHistory";
  @SerializedName(SERIALIZED_NAME_NAME_HISTORY)
  private List<UserNameChange> nameHistory = null;

  public static final String SERIALIZED_NAME_AVATAR_URL = "avatarUrl";
  @SerializedName(SERIALIZED_NAME_AVATAR_URL)
  private String avatarUrl;

  public static final String SERIALIZED_NAME_IS_ORGANIZATION = "isOrganization";
  @SerializedName(SERIALIZED_NAME_IS_ORGANIZATION)
  private Boolean isOrganization;


  public User createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public User name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public User tagline(String tagline) {
    
    this.tagline = tagline;
    return this;
  }

   /**
   * Get tagline
   * @return tagline
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTagline() {
    return tagline;
  }


  public void setTagline(String tagline) {
    this.tagline = tagline;
  }


  public User joinDate(OffsetDateTime joinDate) {
    
    this.joinDate = joinDate;
    return this;
  }

   /**
   * Get joinDate
   * @return joinDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getJoinDate() {
    return joinDate;
  }


  public void setJoinDate(OffsetDateTime joinDate) {
    this.joinDate = joinDate;
  }


  public User roles(List<GlobalRole> roles) {
    
    this.roles = roles;
    return this;
  }

  public User addRolesItem(GlobalRole rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<GlobalRole>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<GlobalRole> getRoles() {
    return roles;
  }


  public void setRoles(List<GlobalRole> roles) {
    this.roles = roles;
  }


  public User projectCount(Long projectCount) {
    
    this.projectCount = projectCount;
    return this;
  }

   /**
   * Get projectCount
   * @return projectCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getProjectCount() {
    return projectCount;
  }


  public void setProjectCount(Long projectCount) {
    this.projectCount = projectCount;
  }


  public User locked(Boolean locked) {
    
    this.locked = locked;
    return this;
  }

   /**
   * Get locked
   * @return locked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getLocked() {
    return locked;
  }


  public void setLocked(Boolean locked) {
    this.locked = locked;
  }


  public User nameHistory(List<UserNameChange> nameHistory) {
    
    this.nameHistory = nameHistory;
    return this;
  }

  public User addNameHistoryItem(UserNameChange nameHistoryItem) {
    if (this.nameHistory == null) {
      this.nameHistory = new ArrayList<UserNameChange>();
    }
    this.nameHistory.add(nameHistoryItem);
    return this;
  }

   /**
   * Get nameHistory
   * @return nameHistory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<UserNameChange> getNameHistory() {
    return nameHistory;
  }


  public void setNameHistory(List<UserNameChange> nameHistory) {
    this.nameHistory = nameHistory;
  }


  public User avatarUrl(String avatarUrl) {
    
    this.avatarUrl = avatarUrl;
    return this;
  }

   /**
   * Get avatarUrl
   * @return avatarUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAvatarUrl() {
    return avatarUrl;
  }


  public void setAvatarUrl(String avatarUrl) {
    this.avatarUrl = avatarUrl;
  }


  public User isOrganization(Boolean isOrganization) {
    
    this.isOrganization = isOrganization;
    return this;
  }

   /**
   * Get isOrganization
   * @return isOrganization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsOrganization() {
    return isOrganization;
  }


  public void setIsOrganization(Boolean isOrganization) {
    this.isOrganization = isOrganization;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.createdAt, user.createdAt) &&
        Objects.equals(this.name, user.name) &&
        Objects.equals(this.tagline, user.tagline) &&
        Objects.equals(this.joinDate, user.joinDate) &&
        Objects.equals(this.roles, user.roles) &&
        Objects.equals(this.projectCount, user.projectCount) &&
        Objects.equals(this.locked, user.locked) &&
        Objects.equals(this.nameHistory, user.nameHistory) &&
        Objects.equals(this.avatarUrl, user.avatarUrl) &&
        Objects.equals(this.isOrganization, user.isOrganization);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, name, tagline, joinDate, roles, projectCount, locked, nameHistory, avatarUrl, isOrganization);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tagline: ").append(toIndentedString(tagline)).append("\n");
    sb.append("    joinDate: ").append(toIndentedString(joinDate)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    projectCount: ").append(toIndentedString(projectCount)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    nameHistory: ").append(toIndentedString(nameHistory)).append("\n");
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("    isOrganization: ").append(toIndentedString(isOrganization)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

