/*
 * Hangar API
 * This page describes the format for the current Hangar REST API as well as general usage guidelines.<br> Note that all routes **not** listed here should be considered **internal**, and can change at a moment's notice. **Do not use them**.  ## Authentication and Authorization There are two ways to consume the API: Authenticated or anonymous.  ### Anonymous When using anonymous authentication, you only have access to public information, but you don't need to worry about creating and storing an API key or handing JWTs.  ### Authenticated If you need access to non-public content or actions, you need to create and use API keys. These can be created by going to the API keys page via the profile dropdown or by going to your user page and clicking on the key icon.  API keys allow you to impersonate yourself, so they should be handled like passwords. **Do not share them with anyone else!**  #### Getting and Using a JWT Once you have an API key, you need to authenticate yourself: Send a `POST` request with your API key identifier to `/api/v1/authenticate?apiKey=yourKey`. The response will contain your JWT as well as an expiration time. Put this JWT into the `Authorization` header of every request and make sure to request a new JWT after the expiration time has passed.  Please also set a meaningful `User-Agent` header. This allows us to better identify loads and needs for potentially new endpoints.  ## Misc ### Date Formats Standard ISO types. Where possible, we use the [OpenAPI format modifier](https://swagger.io/docs/specification/data-models/data-types/#format).  ### Rate Limits and Caching The default rate limit is set at 20 requests every 5 seconds with an initial overdraft for extra leniency. Individual endpoints, such as version creation, may have stricter rate limiting.  If applicable, always cache responses. The Hangar API itself is cached by CloudFlare and internally.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.bentzin.hangar.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * UserPermissions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-28T17:51:10.536335800+01:00[Europe/Berlin]")
public class UserPermissions {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private PermissionType type;

  public static final String SERIALIZED_NAME_PERMISSION_BIN_STRING = "permissionBinString";
  @SerializedName(SERIALIZED_NAME_PERMISSION_BIN_STRING)
  private String permissionBinString;

  public static final String SERIALIZED_NAME_PERMISSIONS = "permissions";
  @SerializedName(SERIALIZED_NAME_PERMISSIONS)
  private List<NamedPermission> permissions = null;


  public UserPermissions type(PermissionType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PermissionType getType() {
    return type;
  }


  public void setType(PermissionType type) {
    this.type = type;
  }


  public UserPermissions permissionBinString(String permissionBinString) {
    
    this.permissionBinString = permissionBinString;
    return this;
  }

   /**
   * Get permissionBinString
   * @return permissionBinString
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPermissionBinString() {
    return permissionBinString;
  }


  public void setPermissionBinString(String permissionBinString) {
    this.permissionBinString = permissionBinString;
  }


  public UserPermissions permissions(List<NamedPermission> permissions) {
    
    this.permissions = permissions;
    return this;
  }

  public UserPermissions addPermissionsItem(NamedPermission permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<NamedPermission>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<NamedPermission> getPermissions() {
    return permissions;
  }


  public void setPermissions(List<NamedPermission> permissions) {
    this.permissions = permissions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserPermissions userPermissions = (UserPermissions) o;
    return Objects.equals(this.type, userPermissions.type) &&
        Objects.equals(this.permissionBinString, userPermissions.permissionBinString) &&
        Objects.equals(this.permissions, userPermissions.permissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, permissionBinString, permissions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserPermissions {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    permissionBinString: ").append(toIndentedString(permissionBinString)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

